import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-slate-100">
        {/* contenedor  */}
        <div className="flex flex-col md:flex-row" >
          {/* div barra de navegacion  */}
          <dic>
            <Navbar />
          </dic>
          {/* div paginas  */}
          <div>{children}</div>
        </div>
      </body>
    </html>
  );
}
